apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: danios149/product-service:latest
        ports:
        - containerPort: 8080  # Port where the app runs
        env:
        - name: DB
          value: "test"
        - name: DB_USER
          value: "test"
        - name: DB_PASSWORD
          value: "test"
        - name: DB_HOST
          value: "postgres-service"  # Kubernetes service for Postgres
