version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_service
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
